-- =====================================================================
-- 03_geography.sql · Banco Andino Colombia
-- Departamentos, municipios (DIVIPOLA) y oficinas.
-- Se ejecuta desde sql/run_all.sql (no abre ni cierra transacción).
-- =====================================================================

-- =====================================================================
-- 3. GEOGRAFÍA
-- =====================================================================

CREATE TABLE ref.departamento (
  departamento_codigo  char(2)     PRIMARY KEY CHECK (departamento_codigo ~ '^[0-9]{2}$'),
  nombre               varchar(80) NOT NULL UNIQUE
);
COMMENT ON TABLE ref.departamento IS 'Departamentos de Colombia con código DIVIPOLA (DANE).';

CREATE TABLE ref.municipio (
  municipio_codigo     char(5)     PRIMARY KEY CHECK (municipio_codigo ~ '^[0-9]{5}$'),
  departamento_codigo  char(2)     NOT NULL REFERENCES ref.departamento (departamento_codigo),
  nombre               varchar(80) NOT NULL,
  CONSTRAINT ck_municipio_prefijo_departamento
    CHECK (left(municipio_codigo, 2) = departamento_codigo),              -- RN-07
  CONSTRAINT uq_municipio_nombre_departamento UNIQUE (departamento_codigo, nombre)
);
COMMENT ON TABLE ref.municipio IS 'Municipios con código DIVIPOLA de 5 dígitos. El código inicia con el del departamento (RN-07). Cargar desde la fuente oficial del DANE; los códigos son texto (conservan el 0 inicial).';

CREATE TABLE ref.oficina (
  oficina_id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo            varchar(10)  NOT NULL UNIQUE,
  nombre            varchar(100) NOT NULL,
  municipio_codigo  char(5)      NOT NULL REFERENCES ref.municipio (municipio_codigo),  -- RN-06
  activa            boolean      NOT NULL DEFAULT true
);
COMMENT ON TABLE ref.oficina IS 'Oficinas del banco (RN-06).';
