-- =====================================================================
-- 04_customers.sql · Banco Andino Colombia
-- Clientes: supertipo y subtipos persona natural / persona jurídica (DM-01).
-- Se ejecuta desde sql/run_all.sql (no abre ni cierra transacción).
-- =====================================================================

-- =====================================================================
-- 5. CLIENTES (supertipo + subtipos)
-- =====================================================================

CREATE TABLE core.cliente (
  cliente_id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_cliente         varchar(10)  NOT NULL CHECK (tipo_cliente IN ('NATURAL', 'JURIDICA')),
  tipo_documento       varchar(5)   NOT NULL,
  numero_documento     varchar(15)  NOT NULL CHECK (numero_documento ~ '^[A-Z0-9]{5,15}$'),
  digito_verificacion  smallint,
  municipio_codigo     char(5)      NOT NULL REFERENCES ref.municipio (municipio_codigo),   -- RN-05
  estado_cliente       varchar(15)  NOT NULL DEFAULT 'ACTIVO' REFERENCES ref.estado_cliente (codigo),
  fecha_vinculacion    date         NOT NULL,
  email                varchar(254) CHECK (email ~* '^[^@\s]+@[^@\s]+\.[a-z]{2,}$'),
  telefono             varchar(20)  CHECK (telefono ~ '^[0-9+ ]{7,20}$'),
  creado_en            timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT uq_cliente_documento UNIQUE (tipo_documento, numero_documento),              -- RN-01
  CONSTRAINT uq_cliente_id_tipo   UNIQUE (cliente_id, tipo_cliente),                      -- destino de FK de subtipos
  CONSTRAINT fk_cliente_tipo_documento FOREIGN KEY (tipo_documento, tipo_cliente)
    REFERENCES ref.tipo_documento (codigo, tipo_cliente),                                  -- RN-03
  CONSTRAINT ck_cliente_nit_numerico
    CHECK (tipo_documento <> 'NIT' OR numero_documento ~ '^[0-9]{9}$'),
  CONSTRAINT ck_cliente_dv_solo_nit
    CHECK ((tipo_documento = 'NIT') = (digito_verificacion IS NOT NULL)),
  CONSTRAINT ck_cliente_dv_valido
    CHECK (digito_verificacion IS NULL
           OR digito_verificacion = ref.fn_dv_nit(numero_documento))                       -- RN-04
);
COMMENT ON TABLE core.cliente IS 'Supertipo de cliente: datos comunes a personas naturales y jurídicas. Documento único (RN-01).';
COMMENT ON COLUMN core.cliente.digito_verificacion IS 'Solo para NIT; validado con ref.fn_dv_nit (RN-04).';

CREATE TABLE core.persona_natural (
  cliente_id        bigint       PRIMARY KEY,
  tipo_cliente      varchar(10)  NOT NULL DEFAULT 'NATURAL' CHECK (tipo_cliente = 'NATURAL'),
  nombres           varchar(120) NOT NULL,
  apellidos         varchar(120) NOT NULL,
  fecha_nacimiento  date         NOT NULL CHECK (fecha_nacimiento >= DATE '1900-01-01'),
  CONSTRAINT fk_persona_natural_cliente FOREIGN KEY (cliente_id, tipo_cliente)
    REFERENCES core.cliente (cliente_id, tipo_cliente)                                     -- RN-02
);
COMMENT ON TABLE core.persona_natural IS 'Subtipo 1:1 de cliente para personas naturales. La FK compuesta impide asociarlo a un cliente jurídico (RN-02).';

CREATE TABLE core.persona_juridica (
  cliente_id           bigint       PRIMARY KEY,
  tipo_cliente         varchar(10)  NOT NULL DEFAULT 'JURIDICA' CHECK (tipo_cliente = 'JURIDICA'),
  razon_social         varchar(200) NOT NULL,
  fecha_constitucion   date         NOT NULL,
  actividad_economica  char(4)      NOT NULL CHECK (actividad_economica ~ '^[0-9]{4}$'),   -- código CIIU
  CONSTRAINT fk_persona_juridica_cliente FOREIGN KEY (cliente_id, tipo_cliente)
    REFERENCES core.cliente (cliente_id, tipo_cliente)                                     -- RN-02
);
COMMENT ON TABLE core.persona_juridica IS 'Subtipo 1:1 de cliente para personas jurídicas (RN-02).';
