-- =====================================================================
-- 06_accounts.sql · Banco Andino Colombia
-- Cuentas, titularidad N:M con vigencia, eventos del ciclo de vida y cambios de límite.
-- Se ejecuta desde sql/run_all.sql (no abre ni cierra transacción).
-- =====================================================================

-- =====================================================================
-- 7. CUENTAS, TITULARIDAD Y EVENTOS
-- =====================================================================

CREATE TABLE core.cuenta (
  cuenta_id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_cuenta         char(11)      NOT NULL UNIQUE CHECK (numero_cuenta ~ '^[0-9]{11}$'),   -- RN-11
  producto_codigo       varchar(20)   NOT NULL REFERENCES core.producto (producto_codigo),     -- RN-12
  moneda_codigo         char(3)       NOT NULL REFERENCES ref.moneda (codigo),
  oficina_id            integer       NOT NULL REFERENCES ref.oficina (oficina_id),
  estado_cuenta         varchar(15)   NOT NULL DEFAULT 'CREADA' REFERENCES ref.estado_cuenta (codigo),
  fecha_apertura        timestamptz   NOT NULL DEFAULT now(),
  fecha_cierre          timestamptz,
  saldo_contable        numeric(18,2) NOT NULL DEFAULT 0,
  saldo_retenido        numeric(18,2) NOT NULL DEFAULT 0 CHECK (saldo_retenido >= 0),          -- RN-19
  saldo_disponible      numeric(18,2) GENERATED ALWAYS AS (saldo_contable - saldo_retenido) STORED,  -- RN-19
  cupo_sobregiro        numeric(18,2) NOT NULL DEFAULT 0 CHECK (cupo_sobregiro >= 0),
  limite_retiro_diario  numeric(18,2) NOT NULL CHECK (limite_retiro_diario > 0),
  CONSTRAINT ck_cuenta_sobregiro
    CHECK (saldo_contable - saldo_retenido >= -cupo_sobregiro),                              -- RN-18
  CONSTRAINT ck_cuenta_cierre_con_fecha
    CHECK ((estado_cuenta = 'CERRADA') = (fecha_cierre IS NOT NULL)),
  CONSTRAINT ck_cuenta_cierre_sin_saldo
    CHECK (estado_cuenta <> 'CERRADA' OR (saldo_contable = 0 AND saldo_retenido = 0)),       -- RN-20
  CONSTRAINT ck_cuenta_fechas
    CHECK (fecha_cierre IS NULL OR fecha_cierre > fecha_apertura)                            -- RN-21
) WITH (fillfactor = 85);
COMMENT ON TABLE core.cuenta IS 'Cuentas bancarias. El saldo es una caché que debe coincidir con los asientos contables (RN-48). fillfactor 85 favorece actualizaciones HOT del saldo.';
COMMENT ON COLUMN core.cuenta.saldo_disponible IS 'Columna generada: saldo_contable - saldo_retenido (RN-19).';

CREATE TABLE core.titularidad_cuenta (
  cuenta_id      bigint       NOT NULL REFERENCES core.cuenta (cuenta_id),
  cliente_id     bigint       NOT NULL REFERENCES core.cliente (cliente_id),
  vigente_desde  timestamptz  NOT NULL DEFAULT now(),
  rol_titular    varchar(10)  NOT NULL CHECK (rol_titular IN ('PRINCIPAL', 'COTITULAR')),
  vigente_hasta  timestamptz,
  PRIMARY KEY (cuenta_id, cliente_id, vigente_desde),
  CONSTRAINT ck_titularidad_vigencia CHECK (vigente_hasta IS NULL OR vigente_hasta > vigente_desde)
);
COMMENT ON TABLE core.titularidad_cuenta IS 'Relación N:M cliente-cuenta con rol y vigencia.';

-- Máximo un titular principal vigente por cuenta (RN-13, parte "máximo uno")
CREATE UNIQUE INDEX uq_titularidad_principal_vigente
  ON core.titularidad_cuenta (cuenta_id)
  WHERE rol_titular = 'PRINCIPAL' AND vigente_hasta IS NULL;

-- Un cliente no puede tener dos titularidades vigentes sobre la misma cuenta
-- (G2, hallazgo H-06: la PK con vigente_desde lo permitía)
CREATE UNIQUE INDEX uq_titularidad_cliente_vigente
  ON core.titularidad_cuenta (cuenta_id, cliente_id)
  WHERE vigente_hasta IS NULL;

CREATE TABLE core.evento_cuenta (
  evento_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cuenta_id        bigint       NOT NULL REFERENCES core.cuenta (cuenta_id),
  tipo_evento      varchar(20)  NOT NULL REFERENCES ref.tipo_evento_cuenta (codigo),
  estado_anterior  varchar(15)  REFERENCES ref.estado_cuenta (codigo),
  estado_nuevo     varchar(15)  NOT NULL REFERENCES ref.estado_cuenta (codigo),
  motivo           varchar(200),
  ocurrido_en      timestamptz  NOT NULL DEFAULT now(),
  registrado_por   bigint       NOT NULL,   -- FK a seg.usuario en 11_constraints.sql
  CONSTRAINT uq_evento_id_tipo UNIQUE (evento_id, tipo_evento),                              -- destino de FK de cambio_limite
  CONSTRAINT fk_evento_transicion FOREIGN KEY (tipo_evento, estado_anterior, estado_nuevo)
    REFERENCES ref.transicion_estado_cuenta (tipo_evento, estado_anterior, estado_nuevo),     -- RN-24
  CONSTRAINT ck_evento_creacion_sin_estado_anterior
    CHECK ((tipo_evento = 'CREACION') = (estado_anterior IS NULL)),
  CONSTRAINT ck_evento_creacion_estado_creada
    CHECK (tipo_evento <> 'CREACION' OR estado_nuevo = 'CREADA'),
  CONSTRAINT ck_evento_bloqueo_con_motivo
    CHECK (tipo_evento <> 'BLOQUEO' OR motivo IS NOT NULL)                                   -- RN-29
);
COMMENT ON TABLE core.evento_cuenta IS 'Historial del ciclo de vida de la cuenta. No mueve dinero (RN-26). Las transiciones válidas se controlan con FK a ref.transicion_estado_cuenta (RN-24).';

CREATE TABLE core.cambio_limite (
  evento_id       bigint        PRIMARY KEY,
  tipo_evento     varchar(20)   NOT NULL DEFAULT 'CAMBIO_LIMITE' CHECK (tipo_evento = 'CAMBIO_LIMITE'),
  valor_anterior  numeric(18,2) NOT NULL CHECK (valor_anterior > 0),
  valor_nuevo     numeric(18,2) NOT NULL CHECK (valor_nuevo > 0),
  CONSTRAINT ck_cambio_limite_distinto CHECK (valor_nuevo <> valor_anterior),                -- RN-27
  CONSTRAINT fk_cambio_limite_evento FOREIGN KEY (evento_id, tipo_evento)
    REFERENCES core.evento_cuenta (evento_id, tipo_evento)
);
COMMENT ON TABLE core.cambio_limite IS 'Detalle de eventos CAMBIO_LIMITE. La FK compuesta impide asociarlo a otro tipo de evento (RN-27).';
