-- =====================================================================
-- 07_users_security.sql · Banco Andino Colombia
-- Usuarios internos, roles y permisos de la aplicación (RBAC, RN-49 a RN-51).
-- Se ejecuta desde sql/run_all.sql (no abre ni cierra transacción).
-- =====================================================================

-- =====================================================================
-- 4. SEGURIDAD (usuarios internos, roles y permisos)
-- =====================================================================

CREATE TABLE seg.usuario (
  usuario_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login             varchar(40)  NOT NULL UNIQUE CHECK (login ~ '^[a-z0-9._]{4,40}$'),
  tipo_documento    varchar(5)   NOT NULL REFERENCES ref.tipo_documento (codigo)
                                 CHECK (tipo_documento IN ('CC', 'CE', 'PA', 'PPT')),
  numero_documento  varchar(15)  NOT NULL CHECK (numero_documento ~ '^[A-Z0-9]{5,15}$'),
  nombres           varchar(120) NOT NULL,
  apellidos         varchar(120) NOT NULL,
  oficina_id        integer      REFERENCES ref.oficina (oficina_id),
  estado            varchar(10)  NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO')),
  creado_en         timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT uq_usuario_documento UNIQUE (tipo_documento, numero_documento)
);
COMMENT ON TABLE seg.usuario IS 'Empleados con acceso al sistema. No tiene relación con core.cliente (RN-10). El documento permite detectar si un usuario opera cuentas propias (RN-54). No almacena contraseñas.';

CREATE TABLE seg.rol (
  rol_id  smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo  varchar(30)  NOT NULL UNIQUE,
  nombre  varchar(80)  NOT NULL
);
COMMENT ON TABLE seg.rol IS 'Roles internos. Los permisos se asignan a roles, no a usuarios (RN-49).';

CREATE TABLE seg.permiso (
  permiso_id   smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo       varchar(40)  NOT NULL UNIQUE,
  descripcion  varchar(150) NOT NULL
);
COMMENT ON TABLE seg.permiso IS 'Acciones autorizables del sistema.';

CREATE TABLE seg.usuario_rol (
  usuario_id     bigint      NOT NULL REFERENCES seg.usuario (usuario_id),
  rol_id         smallint    NOT NULL REFERENCES seg.rol (rol_id),
  vigente_desde  timestamptz NOT NULL DEFAULT now(),
  vigente_hasta  timestamptz,
  asignado_por   bigint      REFERENCES seg.usuario (usuario_id),
  PRIMARY KEY (usuario_id, rol_id, vigente_desde),
  CONSTRAINT ck_usuario_rol_no_autoasignado CHECK (asignado_por <> usuario_id),   -- RN-50
  CONSTRAINT ck_usuario_rol_vigencia CHECK (vigente_hasta IS NULL OR vigente_hasta > vigente_desde)
);
COMMENT ON TABLE seg.usuario_rol IS 'Asignación de roles con vigencia (se revoca con fecha, no se borra). asignado_por NULL solo para la carga inicial del sistema.';

CREATE TABLE seg.rol_permiso (
  rol_id      smallint NOT NULL REFERENCES seg.rol (rol_id),
  permiso_id  smallint NOT NULL REFERENCES seg.permiso (permiso_id),
  PRIMARY KEY (rol_id, permiso_id)
);
COMMENT ON TABLE seg.rol_permiso IS 'Permisos incluidos en cada rol.';

INSERT INTO seg.rol (codigo, nombre) VALUES
  ('CAJERO',          'Cajero'),
  ('SUPERVISOR',      'Supervisor de oficina'),
  ('AUDITOR',         'Auditor'),
  ('ADMIN_SEGURIDAD', 'Administrador de seguridad');

INSERT INTO seg.permiso (codigo, descripcion) VALUES
  ('CLI_CREAR',          'Registrar clientes'),
  ('CLI_ACTUALIZAR',     'Actualizar datos de clientes'),
  ('CTA_ABRIR',          'Abrir cuentas'),
  ('CTA_ACTIVAR',        'Activar cuentas'),
  ('CTA_BLOQUEAR',       'Bloquear cuentas'),
  ('CTA_DESBLOQUEAR',    'Desbloquear cuentas'),
  ('CTA_CERRAR',         'Cerrar cuentas'),
  ('CTA_CAMBIAR_LIMITE', 'Cambiar límites de cuenta'),
  ('CTA_INACTIVAR',      'Inactivar cuentas sin movimiento'),
  ('TX_CONSIGNAR',       'Registrar consignaciones'),
  ('TX_RETIRAR',         'Registrar retiros'),
  ('TX_TRANSFERIR',      'Registrar transferencias'),
  ('TX_DEBITAR',         'Registrar débitos'),
  ('TX_ACREDITAR',       'Registrar créditos'),
  ('TX_AJUSTE_CREAR',    'Crear ajustes'),
  ('TX_AJUSTE_APROBAR',  'Aprobar ajustes'),
  ('TX_REVERSAR',        'Reversar transacciones'),
  ('AUD_CONSULTAR',      'Consultar auditoría'),
  ('SEG_ADMINISTRAR',    'Administrar usuarios, roles y permisos');

-- Matriz rol × permiso (RN-28: desbloquear, cerrar y cambiar límite solo SUPERVISOR;
-- RN-51: CAJERO no reversa ni aprueba ajustes)
INSERT INTO seg.rol_permiso (rol_id, permiso_id)
SELECT r.rol_id, p.permiso_id
FROM (VALUES
  ('CAJERO', 'CLI_CREAR'), ('CAJERO', 'CLI_ACTUALIZAR'), ('CAJERO', 'CTA_ABRIR'),
  ('CAJERO', 'CTA_ACTIVAR'), ('CAJERO', 'CTA_BLOQUEAR'), ('CAJERO', 'TX_CONSIGNAR'),
  ('CAJERO', 'TX_RETIRAR'), ('CAJERO', 'TX_TRANSFERIR'), ('CAJERO', 'TX_DEBITAR'),
  ('CAJERO', 'TX_ACREDITAR'), ('CAJERO', 'TX_AJUSTE_CREAR'),
  ('SUPERVISOR', 'CLI_CREAR'), ('SUPERVISOR', 'CLI_ACTUALIZAR'), ('SUPERVISOR', 'CTA_ABRIR'),
  ('SUPERVISOR', 'CTA_ACTIVAR'), ('SUPERVISOR', 'CTA_BLOQUEAR'), ('SUPERVISOR', 'CTA_DESBLOQUEAR'),
  ('SUPERVISOR', 'CTA_CERRAR'), ('SUPERVISOR', 'CTA_CAMBIAR_LIMITE'), ('SUPERVISOR', 'CTA_INACTIVAR'), ('SUPERVISOR', 'TX_CONSIGNAR'),
  ('SUPERVISOR', 'TX_RETIRAR'), ('SUPERVISOR', 'TX_TRANSFERIR'), ('SUPERVISOR', 'TX_DEBITAR'),
  ('SUPERVISOR', 'TX_ACREDITAR'), ('SUPERVISOR', 'TX_AJUSTE_CREAR'), ('SUPERVISOR', 'TX_AJUSTE_APROBAR'),
  ('SUPERVISOR', 'TX_REVERSAR'),
  ('AUDITOR', 'AUD_CONSULTAR'),
  ('ADMIN_SEGURIDAD', 'SEG_ADMINISTRAR')
) AS m (rol, permiso)
JOIN seg.rol r     ON r.codigo = m.rol
JOIN seg.permiso p ON p.codigo = m.permiso;
