-- =====================================================================
-- 08_transactions.sql · Banco Andino Colombia
-- Transacciones financieras (RN-30 a RN-45).
-- Se ejecuta desde sql/run_all.sql (no abre ni cierra transacción).
-- =====================================================================

-- =====================================================================
-- 8. TRANSACCIONES FINANCIERAS
-- =====================================================================

CREATE TABLE fin.transaccion_financiera (
  transaccion_id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_codigo               varchar(20)   NOT NULL REFERENCES ref.tipo_transaccion (codigo),
  estado_codigo             varchar(20)   NOT NULL REFERENCES ref.estado_transaccion (codigo),
  cuenta_origen_id          bigint        REFERENCES core.cuenta (cuenta_id),
  cuenta_destino_id         bigint        REFERENCES core.cuenta (cuenta_id),
  monto                     numeric(18,2) NOT NULL CHECK (monto > 0),                        -- RN-30
  idempotency_key           uuid          NOT NULL UNIQUE,                                   -- RN-38
  hash_solicitud            bytea,
  transaccion_reversada_id  bigint        UNIQUE REFERENCES fin.transaccion_financiera (transaccion_id),  -- RN-42
  descripcion               varchar(140),
  fecha_solicitud           timestamptz   NOT NULL DEFAULT now(),
  fecha_contabilizacion     timestamptz,
  fecha_contable            date,
  creado_por                bigint        NOT NULL REFERENCES seg.usuario (usuario_id),
  aprobado_por              bigint        REFERENCES seg.usuario (usuario_id),
  motivo_rechazo            varchar(200),

  -- Cuentas coherentes con el tipo (RN-32: origen ≠ destino en transferencias)
  CONSTRAINT ck_tx_cuentas_por_tipo CHECK (
    CASE tipo_codigo
      WHEN 'CONSIGNACION'  THEN cuenta_origen_id IS NULL     AND cuenta_destino_id IS NOT NULL
      WHEN 'CREDITO'       THEN cuenta_origen_id IS NULL     AND cuenta_destino_id IS NOT NULL
      WHEN 'RETIRO'        THEN cuenta_origen_id IS NOT NULL AND cuenta_destino_id IS NULL
      WHEN 'DEBITO'        THEN cuenta_origen_id IS NOT NULL AND cuenta_destino_id IS NULL
      WHEN 'TRANSFERENCIA' THEN cuenta_origen_id IS NOT NULL AND cuenta_destino_id IS NOT NULL
                                AND cuenta_origen_id <> cuenta_destino_id
      ELSE num_nonnulls(cuenta_origen_id, cuenta_destino_id) >= 1          -- AJUSTE, REVERSO
    END
  ),
  -- Solo los reversos referencian otra transacción (RN-41)
  CONSTRAINT ck_tx_reverso_referencia
    CHECK ((tipo_codigo = 'REVERSO') = (transaccion_reversada_id IS NOT NULL)),
  CONSTRAINT ck_tx_no_se_reversa_a_si_misma
    CHECK (transaccion_reversada_id IS NULL OR transaccion_reversada_id <> transaccion_id),
  -- Contabilizada exige fecha de contabilización y fecha contable
  CONSTRAINT ck_tx_posted_con_fechas
    CHECK (estado_codigo <> 'POSTED' OR (fecha_contabilizacion IS NOT NULL AND fecha_contable IS NOT NULL)),
  -- Y al revés: rechazada o pendiente no tiene fechas contables (G2, hallazgo H-07)
  CONSTRAINT ck_tx_fechas_solo_posted
    CHECK (estado_codigo = 'POSTED' OR (fecha_contabilizacion IS NULL AND fecha_contable IS NULL)),
  -- Rechazada exige motivo (RN-45)
  CONSTRAINT ck_tx_rechazo_con_motivo
    CHECK (estado_codigo <> 'REJECTED' OR motivo_rechazo IS NOT NULL),
  -- Solo los ajustes pueden quedar pendientes de aprobación
  CONSTRAINT ck_tx_pendiente_solo_ajuste
    CHECK (estado_codigo <> 'PENDING_APPROVAL' OR tipo_codigo = 'AJUSTE'),
  -- Ajuste contabilizado requiere aprobador distinto del creador (RN-44)
  CONSTRAINT ck_tx_ajuste_aprobado
    CHECK (NOT (tipo_codigo = 'AJUSTE' AND estado_codigo = 'POSTED') OR aprobado_por IS NOT NULL),
  CONSTRAINT ck_tx_aprobador_distinto
    CHECK (aprobado_por IS NULL OR aprobado_por <> creado_por),
  -- Solo los ajustes llevan aprobador (G2, hallazgo H-08)
  CONSTRAINT ck_tx_aprobador_solo_ajuste
    CHECK (aprobado_por IS NULL OR tipo_codigo = 'AJUSTE')
);
COMMENT ON TABLE fin.transaccion_financiera IS 'Movimientos de dinero. POSTED es inmutable (RN-40, se protege con triggers en G3). Los errores se corrigen con REVERSO (RN-41).';
COMMENT ON COLUMN fin.transaccion_financiera.idempotency_key IS 'Identificador único de la solicitud: una solicitud repetida no genera un segundo movimiento (RN-38).';
COMMENT ON COLUMN fin.transaccion_financiera.hash_solicitud IS 'Huella del contenido de la solicitud para detectar reutilización de la clave con otros datos.';
